#include "control_cards.h"

#include <array>

constexpr bool T = true;
constexpr bool F = false;
const std::array<std::array<bool, 133>, 95> control_cards{{
    {
        F, T, F, F, F, T, F, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F, T,
        F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F,
        F, F, F, T, T, F, T, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T,
        F, F, F, F, F, F, T, T, F, T, F, T, F, F, T, F, T, F, F, F, F, T, F,
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F,
    },
    {
        F, T, T, T, T, T, F, F, F, F, F, T, F, F, T, T, T, T, T, T, F, F, F,
        T, T, T, T, F, F, T, F, F, T, F, F, T, F, F, F, F, F, F, T, T, T, T,
        T, T, F, T, F, F, F, T, F, F, F, T, T, F, F, T, T, T, F, T, F, T, T,
        F, F, F, T, T, F, F, F, F, F, T, T, F, T, T, F, T, F, T, T, F, T, F,
        T, T, T, F, T, F, T, T, T, F, T, T, F, F, F, T, F, F, F, T, T, F, T,
        F, F, T, F, T, F, F, T, T, F, F, F, F, T, F, F, T, F,
    },
    {
        F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F,
        T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T,
        F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F,
    },
    {
        F, T, T, F, T, F, F, T, T, F, T, T, F, F, T, T, F, T, T, T, F, F, F,
        F, F, F, T, T, F, F, T, T, F, T, T, T, F, T, F, T, T, F, F, F, F, F,
        T, T, T, T, T, T, F, F, T, T, F, T, T, T, F, F, F, F, T, F, F, F, T,
        F, F, F, T, T, T, T, T, F, F, T, F, F, T, F, F, F, F, T, T, F, T, T,
        F, T, F, F, T, T, F, T, T, T, F, T, F, T, T, F, F, T, T, T, F, T, F,
        F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, T, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F,
        F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F,
        F, F, T, T, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, T, F, F,
    },
    {
        F, F, F, F, F, F, F, T, T, F, T, F, T, T, F, F, F, T, F, F, F, T, T,
        F, F, F, T, F, F, F, F, F, T, T, T, F, T, T, F, F, T, F, F, F, F, F,
        F, F, F, F, F, T, T, F, T, T, T, T, F, T, T, F, T, F, F, F, T, F, F,
        T, F, F, F, F, T, T, T, T, T, F, F, F, F, T, T, T, T, F, F, F, T, T,
        F, T, T, F, F, F, F, F, T, T, F, F, F, T, F, F, T, F, T, F, F, T, F,
        F, T, F, T, F, T, F, F, T, F, F, F, F, F, F, T, F, F,
    },
    {
        F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, T, F, F, T, T, F, T, F, T, T, F, F, F, F, F, F,
        F, F, T, F, F, F, F, F, T, T, T, F, F, F, F, F, F, F, T, F, F, F, F,
        F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, T,
        F, F, F, T, F, T, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, F, T, F, F, F, F, T, T, F, F, T, F, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, T, T, F, F, F, T,
        T, T, F, F, F, F, T, F, F, F, T, F, F, T, F, T, F, F, F, F, F, T, F,
        F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, T, T, T, T,
        F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, T, F, F, F, F,
        F, T, T, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, T, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, T, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, T, T, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F, F, T,
        F, F, F, F, F, T, F, T, F, F, F, F, F, F, T, F, F, F, T, F, F, T, T,
        F, F, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F, T, T, F, T, T, F,
        F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, T,
        F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, T, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, T, F, F, T, F,
        F, F, F, T, T, F, T, F, F, T, F, T, F, F, F, F, T, F, F, T, T, T, T,
        F, T, F, F, F, F, F, F, F, T, F, T, T, F, F, F, F, F, T, F, F, F, F,
        F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, T, F, F, F, T, F, F, F,
        F, T, T, F, T, F, F, F, F, T, F, F, F, F, F, T, F, F, T, F, F, F, F,
        F, F, T, T, T, T, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, T, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, F, T, F, T, T, F, F, T, T, F, F, F, T, F, F, F,
        F, F, F, T, T, F, F, T, T, F, F, F, T, F, F, F, T, T, F, F, F, F, F,
        T, T, T, F, F, T, F, F, T, T, F, F, T, F, F, F, F, F, F, F, F, F, F,
        F, F, F, T, T, F, T, T, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F,
        F, T, F, F, F, F, F, T, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F,
    },
    {
        F, F, F, F, F, F, F, F, T, F, F, T, F, F, T, F, F, F, F, F, F, T, T,
        F, F, F, F, T, T, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, T, T, F, F, F, F, T, T, F, F, F, T, F, F, T, F, T,
        F, F, F, F, F, F, F, T, F, F, F, F, T, F, T, T, F, T, F, T, F, F, F,
        F, T, F, F, T, F, T, F, T, F, F, F, F, F, T, T, F, F, T, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T,
        F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, T, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, T, T, F, T, F, T, F, F, T, T, F, F, F, T, T, F, T, F, F, T,
        T, T, F, F, F, T, F, F, T, F, T, F, F, T, T, T, F, F, T, F, F, F, F,
        T, F, F, T, F, F, F, T, F, F, F, F, F, F, T, T, F, T, F, T, T, T, T,
        T, T, F, T, F, F, F, T, T, T, F, F, T, F, F, F, F, T, T, F, T, T, T,
        F, F, F, T, F, F, T, T, F, F, F, T, F, F, T, F, T, T, F, T, T, T, T,
        F, T, F, F, F, F, T, F, T, F, F, T, T, F, T, T, F, F,
    },
    {
        F, F, T, T, T, T, F, F, F, F, F, T, F, F, T, T, T, F, T, T, F, F, F,
        T, T, T, F, F, F, T, T, F, F, F, F, T, F, F, F, T, F, F, F, T, T, T,
        F, T, T, F, F, F, F, T, F, F, F, F, T, F, F, F, F, T, T, T, F, F, F,
        F, T, F, T, T, F, F, F, F, F, T, T, F, T, F, F, F, F, F, T, T, F, F,
        T, F, F, T, T, T, F, T, F, F, F, T, F, F, F, F, F, T, F, T, T, F, T,
        F, F, T, F, T, F, F, T, F, F, F, F, T, T, F, F, F, F,
    },
    {
        F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, T, F, F, F, F, T, F, F, F, T, F, F, F, F, T, F, F, F, F, F, T,
        F, T, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F,
        F, T, T, T, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F,
        T, F, F, T, F, T, F, F, F, F, F, T, F, T, F, F, F, T, F, F, T, F, F,
        F, F, T, F, F, F, T, T, F, F, F, T, T, T, F, F, T, F,
    },
    {
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F,
        T, T, F, F, F, F, F, F, T, F, T, T, F, T, F, T, T, T, F, F, F, T, T,
        F, T, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, F,
        F, F, T, T, F, F, F, F, F, F, T, T, F, F, F, F, F, T, F, T, F, F, F,
        F, T, T, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F,
    },
    {
        F, T, F, F, F, F, F, F, F, F, T, T, T, T, T, F, T, T, F, T, F, F, T,
        F, F, F, T, F, F, T, F, F, T, F, F, T, F, T, F, F, F, T, T, T, F, F,
        F, F, F, T, F, T, T, F, F, F, F, T, F, T, T, T, F, T, F, T, T, T, T,
        T, F, F, F, F, T, T, T, T, T, T, F, T, F, T, T, T, T, F, F, F, T, F,
        F, T, F, F, T, F, T, T, T, T, F, F, F, F, F, F, T, F, F, F, F, T, F,
        F, F, F, T, T, T, F, F, T, F, F, F, F, F, F, F, F, F,
    },
    {
        F, T, T, T, T, T, T, F, F, F, F, T, F, F, F, F, T, F, T, T, F, F, T,
        T, T, F, T, F, F, T, F, F, T, T, F, F, T, F, T, F, F, T, F, T, T, F,
        T, F, F, T, F, F, F, F, T, T, T, F, F, F, T, T, T, T, F, F, T, F, T,
        T, T, F, T, F, F, F, F, F, T, T, F, T, F, F, T, F, F, T, F, T, T, T,
        T, T, T, F, T, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, T, T, T,
        F, F, F, F, T, T, F, F, T, F, F, T, F, T, F, T, T, F,
    },
    {
        F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, T, T, F, T, T, F, F, F,
        T, T, T, F, F, F, F, F, T, F, T, F, T, F, F, T, T, T, T, T, T, T, T,
        F, T, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F,
        F, T, F, T, T, F, F, F, F, T, T, T, F, F, F, F, F, F, T, F, T, F, F,
        T, F, F, T, T, T, F, T, F, F, T, T, F, F, F, F, F, T, F, T, T, F, F,
        F, T, T, T, T, F, T, F, F, F, F, F, F, T, T, F, F, F,
    },
    {
        F, F, T, T, T, T, T, T, T, F, F, T, T, F, T, T, T, T, F, T, F, F, T,
        T, T, T, F, F, T, F, T, T, F, T, F, F, T, T, T, F, T, T, F, F, F, F,
        T, F, T, T, T, T, T, T, T, F, T, F, F, T, T, T, T, T, F, T, T, T, T,
        T, T, T, T, T, F, F, T, T, T, F, T, T, T, T, F, F, T, T, F, T, T, T,
        T, F, F, T, F, T, T, T, T, F, T, T, F, T, T, F, T, T, F, T, T, T, T,
        F, T, F, F, F, F, T, T, T, F, F, T, T, T, T, T, T, F,
    },
    {
        F, F, F, F, F, F, F, T, T, F, T, F, F, T, F, F, F, F, F, F, F, T, T,
        F, F, F, F, T, T, F, T, T, F, F, T, F, F, T, F, T, T, T, F, F, F, F,
        F, F, T, F, T, T, T, F, F, F, T, F, F, T, F, F, F, F, T, F, T, F, F,
        F, T, T, F, F, T, T, T, T, T, F, F, T, F, F, T, F, T, F, F, T, F, F,
        F, F, F, T, F, T, F, F, F, F, F, F, F, T, T, F, T, T, T, F, F, F, F,
        F, T, F, T, F, T, T, F, F, F, F, T, T, F, T, F, F, F,
    },
    {
        F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F,
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, T, T, T, F, F, F, F, F, F, F, F, F, F, F, F,
        T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F,
    },
    {
        F, F, F, T, F, F, T, T, F, F, T, T, T, F, F, F, T, T, F, T, F, F, F,
        T, T, F, T, T, T, F, F, T, T, F, T, F, T, F, T, F, F, T, F, F, F, F,
        F, F, T, F, F, T, F, F, T, T, T, T, F, T, T, T, T, T, F, T, T, T, F,
        T, F, F, T, F, T, F, F, T, F, F, F, T, T, F, T, F, T, F, T, T, F, F,
        F, T, T, T, F, F, F, F, T, T, F, T, F, T, F, F, T, T, T, T, T, F, T,
        F, F, F, F, F, T, F, F, T, F, F, T, T, F, T, T, T, F,
    },
    {
        F, T, T, F, F, F, F, F, T, F, F, F, F, T, T, T, F, F, T, F, F, T, F,
        F, F, T, F, F, F, F, T, F, F, T, F, T, F, T, F, T, T, F, T, F, F, T,
        T, T, F, F, T, F, T, T, F, F, F, F, T, F, F, F, F, F, T, F, F, F, F,
        F, F, T, F, T, F, T, T, F, F, T, T, F, F, T, F, T, F, T, F, F, T, T,
        F, F, F, F, T, T, T, F, F, F, T, F, F, F, T, T, F, F, F, F, F, T, F,
        F, T, T, T, F, F, T, T, F, F, F, F, F, T, F, F, F, F,
    },
    {
        F, F, F, T, F, F, T, F, T, F, T, T, T, T, F, F, F, T, F, F, F, T, T,
        F, F, F, F, T, T, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F,
        T, F, T, F, F, T, T, T, T, T, T, F, F, T, T, F, T, F, F, F, T, F, T,
        T, F, T, F, F, T, F, T, F, F, F, F, T, F, T, T, F, T, F, T, F, T, T,
        F, T, F, F, F, F, T, F, T, T, F, F, F, T, T, T, F, F, T, F, F, T, F,
        F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, T, F, F,
    },
    {
        F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, T, F, T, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F,
        T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, T, F, F,
        T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, F, F, F, F, F, T, T, F, F, F, F, F,
    },
    {
        F, F, F, T, T, F, T, T, F, F, F, F, T, F, F, F, F, T, F, F, F, T, F,
        F, T, T, F, T, F, F, T, T, F, T, T, F, T, F, T, T, F, F, F, F, F, T,
        T, F, T, F, F, F, F, F, T, T, T, F, F, F, F, F, T, F, T, F, F, F, F,
        F, T, T, T, F, F, F, F, F, F, F, F, F, T, F, T, F, F, T, F, T, F, T,
        F, F, T, T, F, T, F, F, F, T, F, T, F, T, F, F, F, T, T, F, F, F, F,
        F, T, T, F, F, T, T, T, F, F, F, T, T, F, F, T, T, F,
    },
    {
        F, T, F, T, T, T, F, T, F, F, F, F, F, T, F, T, F, T, F, F, F, T, T,
        F, T, T, F, T, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, T, T, T,
        T, F, F, T, T, F, T, T, F, F, F, F, T, F, F, F, T, F, F, F, F, F, T,
        F, F, F, T, F, F, T, T, F, T, F, T, F, T, T, T, T, F, T, F, F, T, F,
        F, F, T, F, F, F, F, T, F, T, F, T, F, F, T, F, F, F, T, F, F, T, F,
        F, T, T, F, F, T, F, T, F, F, F, F, F, T, F, F, T, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, T, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, T, F, F, F, F,
        T, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F, T, F, T,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, T, T, F,
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F,
        F, T, F, T, F, F, F, F, T, F, F, T, F, T, F, F, F, F, T, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, T, F,
    },
    {
        F, T, T, T, T, T, F, T, F, F, T, T, F, T, T, T, T, T, T, T, F, F, F,
        T, T, T, T, F, F, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T,
        T, T, T, T, T, F, F, T, F, T, T, T, T, F, F, T, T, T, T, T, F, T, T,
        F, T, T, T, T, T, T, F, T, T, T, T, F, T, T, F, T, F, T, T, T, T, F,
        T, T, T, T, T, T, T, T, T, F, T, T, F, T, F, T, T, T, F, T, T, F, T,
        F, T, T, T, T, T, T, T, T, F, F, T, T, T, T, F, T, F,
    },
    {
        F, T, T, T, T, T, F, T, T, F, T, T, F, T, T, T, T, T, T, T, F, T, T,
        T, T, T, T, T, T, T, F, T, T, F, F, T, F, T, F, F, T, T, T, T, T, T,
        T, T, F, T, T, T, T, T, F, F, F, T, T, T, T, T, T, T, F, T, T, T, T,
        T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, F,
        T, T, T, F, T, F, T, T, T, T, T, T, F, F, T, T, T, F, T, T, T, T, T,
        F, T, T, T, T, T, F, T, T, F, F, F, F, T, T, F, T, F,
    },
    {
        F, F, T, T, T, T, T, F, T, F, F, T, F, F, T, F, F, F, F, F, F, T, T,
        F, F, T, F, T, T, T, T, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F,
        T, T, T, F, F, F, F, T, F, F, F, F, T, F, F, F, F, T, T, T, F, F, T,
        F, T, T, T, T, F, F, F, F, F, T, F, T, T, F, F, F, F, F, T, T, F, T,
        T, F, F, F, T, T, T, T, F, F, F, F, F, F, T, T, F, F, F, F, T, F, T,
        F, F, T, F, T, F, F, T, F, F, F, F, T, T, F, F, F, F,
    },
    {
        F, T, F, F, F, F, F, T, F, F, T, F, T, T, F, T, T, T, T, T, F, F, F,
        T, T, F, T, F, F, F, F, T, T, T, T, T, T, F, T, T, T, T, T, T, F, T,
        F, F, F, T, T, T, T, F, T, T, T, T, F, T, T, T, T, F, F, F, T, T, F,
        T, F, F, F, F, T, T, T, T, T, F, T, F, F, T, T, T, T, T, F, F, T, F,
        F, T, T, T, F, F, F, F, T, T, T, T, F, T, F, F, T, T, T, T, F, T, F,
        F, T, F, T, F, T, T, F, T, F, F, T, F, F, T, T, T, F,
    },
    {
        F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F,
        F, F, T, F, F, F, F, F, F, F, T, F, T, F, F, F, T, T, F, T, T, F, T,
        F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, T, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F,
        T, F, F, F, T, T, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F,
        F, T, F, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, T, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, T, T, F, F, F, F, T, F, F, F, F, F, F, F, F,
        T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T,
        F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F,
    },
    {
        F, T, T, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F,
        F, F, F, T, F, F, T, T, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, T, F, T, F, F, F, T, F,
        F, F, F, F, F, F, T, F, T, F, F, F, F, T, F, F, T, F, F, F, F, F, F,
        F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T,
        F, F, F, F, F, F, F, T, F, F, F, T, T, F, F, F, T, F,
    },
    {
        F, T, F, F, F, T, F, F, F, F, T, T, F, T, T, T, T, F, F, T, F, F, T,
        F, F, F, F, F, F, T, F, F, F, F, F, T, F, T, F, F, F, T, T, T, T, F,
        F, F, F, T, T, T, T, T, F, F, F, T, T, F, T, T, F, T, F, T, F, F, T,
        F, F, F, F, F, F, T, T, T, T, T, T, T, F, T, F, T, T, F, F, F, T, F,
        F, F, F, F, T, F, T, T, T, F, F, F, F, F, T, F, F, F, F, F, F, T, F,
        F, F, F, T, T, F, F, F, T, F, F, F, F, T, F, F, F, F,
    },
    {
        F, F, T, T, T, T, T, F, F, F, F, F, T, F, F, F, F, T, T, F, F, F, F,
        T, T, T, F, F, F, F, T, F, F, T, T, F, T, F, T, T, F, F, F, F, T, T,
        T, T, T, F, F, F, F, F, T, T, T, F, F, F, F, F, T, F, T, T, F, T, F,
        F, T, T, T, T, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, T, F, T,
        T, F, T, T, F, T, F, T, F, F, F, T, F, T, F, F, F, T, F, F, T, F, T,
        F, F, T, F, F, F, T, T, F, F, F, T, T, T, F, T, T, F,
    },
    {
        F, F, F, T, T, T, F, F, F, F, T, T, F, T, F, F, F, T, T, F, F, F, F,
        F, F, T, F, F, F, F, F, F, T, T, F, T, F, F, F, T, T, F, T, T, F, T,
        T, F, T, T, F, F, F, T, F, T, T, F, F, F, F, F, T, F, F, F, F, F, T,
        F, T, T, F, T, T, F, F, F, T, F, F, F, F, T, F, F, F, T, T, F, T, F,
        T, T, F, F, T, T, T, T, T, F, T, F, F, T, F, T, F, F, F, F, F, F, F,
        F, T, F, T, T, T, T, F, T, F, F, F, F, F, F, F, F, F,
    },
    {
        F, T, T, T, T, T, T, T, T, F, F, T, T, F, T, T, T, T, T, T, F, T, T,
        T, T, F, T, T, T, T, F, T, T, T, T, F, T, T, T, T, T, T, F, T, T, T,
        T, T, F, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T,
        T, T, F, T, F, F, F, T, F, T, T, T, T, F, T, T, F, T, T, T, T, T, T,
        T, T, T, T, T, F, T, T, T, T, T, T, F, F, T, T, T, T, T, T, T, T, T,
        F, T, T, F, T, T, T, F, T, F, F, T, F, T, T, T, T, F,
    },
    {
        F, F, F, F, F, F, F, T, F, F, T, F, T, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, T, F, T, F, F, T, F, T, F, T, T, F, F, F, F,
        F, F, F, F, T, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F,
        T, F, F, F, F, T, T, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, F, T, F,
        F, T, F, T, F, T, F, F, F, F, F, F, F, F, T, F, F, F,
    },
    {
        F, F, F, F, F, F, F, T, T, F, T, F, T, T, T, T, F, T, F, F, F, T, F,
        F, F, T, F, T, T, F, T, T, F, F, T, T, F, T, F, T, T, F, T, F, F, T,
        F, T, T, F, T, T, T, T, F, F, F, T, T, T, F, F, F, F, T, T, F, T, F,
        F, F, T, F, T, T, T, T, T, F, F, T, F, T, T, F, T, T, F, T, F, F, F,
        F, F, F, T, F, T, T, T, T, F, T, T, F, T, T, T, F, T, T, T, F, F, F,
        F, T, T, T, F, F, T, T, F, F, F, F, T, F, T, F, F, F,
    },
    {
        F, T, T, F, F, F, T, T, T, F, T, T, T, F, T, T, T, F, T, T, F, F, F,
        T, F, F, T, T, T, F, T, T, F, T, T, T, T, T, T, T, T, T, F, F, F, F,
        F, T, T, F, T, T, F, F, T, T, F, T, T, T, T, T, F, T, T, T, T, T, F,
        T, F, F, T, T, T, T, T, T, F, T, F, T, T, F, F, F, T, F, T, T, F, T,
        F, T, F, T, T, T, F, F, T, T, F, T, F, T, T, F, T, T, T, T, T, T, T,
        F, F, F, T, F, F, F, F, F, F, F, T, T, T, T, T, T, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, T, T, F, T, F, F, T, T, T, F, F, F, F, F, T, F,
        F, F, T, F, T, T, F, T, T, F, F, T, T, F, T, F, T, T, F, T, F, F, T,
        F, T, T, F, T, T, T, T, F, F, F, T, T, T, F, F, F, F, T, F, F, F, F,
        F, F, T, F, T, T, T, T, T, F, F, T, F, T, T, F, T, T, F, T, F, F, F,
        F, F, F, T, F, T, T, F, T, F, T, T, F, T, T, T, F, T, T, T, F, F, F,
        F, T, T, T, F, F, T, T, F, F, F, F, T, F, T, F, F, F,
    },
    {
        F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, T, F, F, F, F, F, F,
        T, F, F, F, F, T, F, F, F, F, F, F, F, T, F, T, F, F, T, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, T, F, T, T, T, F,
        T, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, T, F, F, T, F, F,
        F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, T,
        F, F, F, F, F, F, F, F, F, F, F, T, T, F, T, T, F, F,
    },
    {
        F, T, T, F, F, F, T, T, T, F, F, F, T, F, T, T, T, F, F, T, F, T, T,
        T, T, F, T, T, T, T, T, T, F, F, T, F, T, T, T, F, F, T, F, F, T, F,
        F, T, F, F, T, T, T, F, T, F, F, T, T, T, T, T, F, T, T, T, T, T, F,
        T, F, F, T, F, F, T, T, T, F, T, T, T, T, F, T, T, T, F, F, T, F, T,
        F, F, T, T, F, F, F, F, F, T, F, T, F, F, T, F, T, T, T, T, T, T, T,
        F, F, T, F, F, F, F, T, F, F, F, T, T, T, T, T, T, F,
    },
    {
        F, T, T, F, F, F, F, T, T, F, T, T, F, F, T, T, F, F, T, T, F, F, F,
        F, F, F, T, T, F, F, T, T, F, T, T, T, F, T, F, T, T, F, F, F, F, F,
        F, T, T, F, T, T, F, F, T, T, F, T, T, T, F, F, F, F, T, F, F, F, F,
        F, F, F, T, T, T, T, T, F, F, T, F, F, T, F, F, F, F, F, T, F, F, T,
        F, T, F, F, T, T, F, F, T, T, F, T, F, T, T, F, F, T, T, T, F, T, F,
        F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, T, F,
    },
    {
        F, F, T, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, F, F,
        T, F, F, T, F, T, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F,
        F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, T, F,
        T, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F,
        T, T, F, F, F, F, F, F, F, F, T, F, F, F, F, T, T, F, F, T, T, F, T,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F,
    },
    {
        F, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F, F, F, F,
        F, F, F, T, T, F, F, F, F, F, T, T, F, F, F, F, F, F, T, T, F, F, T,
        T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, T, F, F, F,
        F, F, F, F, F, T, F, F, T, F, F, T, F, F, T, F, F, F, F, T, F, F, F,
        F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, T, F, F,
    },
    {
        F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T,
        F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F,
        F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T,
        F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F,
        T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, T, F, F, T, F, F, T, F, T, T, F, T, T, F, F, F,
        T, T, F, T, F, F, F, F, T, F, T, T, T, T, F, T, T, T, T, T, T, T, T,
        F, T, F, T, T, F, F, F, F, T, F, T, F, F, F, F, F, F, T, F, F, F, F,
        F, F, F, F, F, T, T, F, T, T, T, T, F, F, F, F, T, F, T, F, F, F, F,
        F, F, T, T, F, F, F, F, F, F, T, T, F, F, F, F, T, T, F, T, F, F, F,
        F, T, T, T, F, T, T, F, F, F, F, F, F, F, T, F, F, F,
    },
    {
        F, T, T, T, F, T, T, F, T, F, F, T, T, F, T, F, F, T, F, F, F, T, T,
        F, F, F, F, T, T, T, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F,
        T, F, F, F, F, T, T, T, T, F, F, F, T, T, T, T, T, T, F, T, T, T, T,
        T, F, F, F, F, F, F, T, F, F, F, F, T, F, T, T, F, T, F, T, F, T, T,
        F, T, F, F, T, F, T, T, T, T, F, F, F, F, T, T, F, F, T, F, F, T, T,
        F, F, F, F, T, F, F, F, T, F, F, F, F, F, F, T, F, F,
    },
    {
        F, T, F, T, F, T, T, T, F, F, T, T, T, T, F, T, T, F, T, F, F, F, F,
        T, F, T, F, T, T, F, F, T, F, T, F, T, T, F, T, T, T, T, F, T, F, T,
        F, F, T, F, T, F, F, T, F, T, F, F, T, F, T, T, T, T, F, T, T, T, F,
        T, F, F, T, T, T, T, T, T, T, F, F, T, T, T, F, F, T, F, T, T, F, F,
        F, T, F, T, T, T, F, F, T, T, F, T, F, T, T, F, T, F, T, F, T, T, T,
        F, T, F, T, F, T, F, F, F, F, F, T, T, T, T, T, T, F,
    },
    {
        F, F, F, T, F, F, F, T, F, F, F, T, T, F, T, T, F, T, F, T, F, F, T,
        F, T, F, F, F, T, F, F, F, F, T, T, T, F, F, F, F, F, F, F, F, F, T,
        F, T, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F, T, F, T, F,
        F, T, F, T, T, T, F, F, T, T, F, F, F, F, T, F, T, T, F, F, F, F, T,
        F, F, F, T, F, F, F, T, F, F, T, F, F, T, F, T, F, F, T, F, F, T, F,
        F, F, F, F, F, F, F, T, T, F, F, F, T, F, T, F, F, F,
    },
    {
        F, F, F, F, F, F, T, F, T, F, F, F, T, F, F, F, F, F, F, F, F, T, T,
        F, F, F, F, T, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, T, F, T, F, F, F, F, T, T, F, F, F, F, F, T, F, F,
        T, F, F, F, F, F, F, T, F, F, F, F, T, F, F, T, F, T, F, F, F, F, T,
        F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, T, F, F, T, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F,
    },
    {
        F, F, F, T, F, T, T, F, F, F, F, F, T, T, F, F, T, F, F, F, F, T, T,
        T, T, T, F, F, T, T, F, F, T, F, F, F, T, F, T, F, F, T, T, T, T, T,
        F, F, F, F, F, F, T, T, F, F, T, F, F, F, T, T, T, T, F, T, T, T, F,
        T, T, T, F, F, F, F, F, T, T, F, T, T, F, T, T, T, T, F, F, T, F, F,
        T, F, T, T, F, F, T, F, F, F, T, F, F, F, F, T, T, F, F, F, T, F, T,
        F, T, T, F, T, T, T, T, T, F, F, T, T, F, T, T, F, F,
    },
    {
        F, F, F, F, F, F, F, T, F, F, T, F, F, T, F, T, T, F, F, T, F, F, F,
        F, F, F, T, F, F, F, F, T, F, F, F, T, F, F, F, F, T, T, T, T, F, F,
        F, F, F, T, T, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, T, T, F, T, T, T, T, F, F, F, F, T, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, T, F, F, F,
        F, T, F, T, F, T, F, F, F, F, F, F, F, F, T, F, F, F,
    },
    {
        F, F, F, F, T, F, T, F, F, F, T, F, F, F, F, F, F, F, T, F, F, T, F,
        T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F,
        T, F, T, T, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, T, T, F,
        F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, T, F, F, F, T, T, F,
        F, T, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, T, T, F, F, F, T, F, F, F, F, T, F, F, F, F, F,
    },
    {
        F, T, F, F, F, F, F, F, F, F, T, F, F, T, T, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, T, F, F, T, F, T, F, F, F, F, T, F, F, F,
        F, F, F, F, F, T, T, F, F, F, F, T, F, T, T, T, F, F, F, F, F, F, F,
        T, F, F, F, F, T, T, T, T, F, F, F, F, F, T, F, T, T, F, F, F, T, F,
        F, F, F, F, F, F, T, F, T, T, F, F, F, F, F, F, F, F, F, F, F, T, F,
        F, F, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, F,
    },
    {
        F, T, F, F, F, F, F, T, F, F, T, F, F, T, T, T, T, F, F, T, F, F, F,
        F, F, F, T, F, F, F, F, T, T, F, F, T, F, T, F, F, T, T, T, T, F, F,
        F, F, F, T, T, T, T, F, F, F, F, T, F, T, T, T, F, F, F, F, F, F, F,
        T, F, F, F, F, T, T, T, T, T, T, T, F, F, T, F, T, T, F, F, F, T, F,
        F, F, F, F, F, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T, F, T, F,
        F, T, F, T, T, T, F, F, T, F, F, F, F, F, T, F, F, F,
    },
    {
        F, F, F, T, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, T,
        F, T, T, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, T, T, T, T,
        F, F, F, F, F, F, T, T, F, F, T, F, F, F, F, F, T, F, F, F, F, F, F,
        F, T, T, F, F, F, F, F, F, T, F, T, F, F, T, T, T, F, F, F, F, F, F,
        T, F, T, F, F, F, T, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F,
        F, T, T, F, T, T, T, T, T, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, T, F, T, F, F, F, T, F, F, F, F, F, T, F, F, F, F, F, F, T, T,
        F, F, F, F, F, F, T, T, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F,
        T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T,
        F, T, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, T,
        T, F, F, F, F, F, T, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F,
        F, F, T, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F,
        T, T, T, F, F, F, F, T, T, F, T, T, F, T, F, T, T, T, F, F, F, T, T,
        F, T, T, F, T, F, F, F, F, T, T, F, F, F, F, F, F, F, T, F, F, F, F,
        F, T, T, T, T, F, F, F, F, F, F, T, F, T, F, F, F, F, T, F, T, F, F,
        T, F, T, T, F, T, F, F, F, F, T, T, F, T, F, F, F, T, F, T, T, F, F,
        F, T, T, F, F, F, T, T, F, F, F, T, T, T, T, F, T, F,
    },
    {
        F, T, F, F, F, F, F, T, F, F, T, F, T, T, F, T, T, T, T, T, F, F, F,
        T, T, F, T, F, F, F, F, T, T, T, F, T, T, F, T, F, T, T, T, T, T, F,
        F, F, F, T, T, F, F, F, F, T, F, T, F, F, T, T, F, F, F, T, F, T, F,
        T, F, F, F, F, T, T, F, T, T, T, T, F, F, F, F, T, F, T, F, F, T, F,
        F, F, T, F, F, F, F, T, F, T, T, F, F, F, F, F, T, F, F, T, F, T, F,
        F, T, F, T, T, T, F, F, T, F, F, F, F, F, T, F, F, F,
    },
    {
        F, F, F, T, T, T, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F, T, T,
        F, T, T, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, T, T, T, T,
        T, F, F, T, F, F, T, T, F, F, T, F, F, F, F, F, T, F, F, F, F, F, T,
        F, T, T, F, F, F, F, F, F, T, F, T, F, F, T, T, T, F, T, F, F, T, F,
        T, F, T, F, F, F, T, T, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F,
        F, T, T, F, T, T, T, T, T, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, T, T, T, T, F, F, F, T, T, T, T, F, F, F, T, F, T, F, T, T,
        F, T, T, F, T, F, F, F, T, F, T, F, F, F, T, T, F, F, T, T, F, T, F,
        T, F, T, T, T, T, T, T, T, T, T, F, F, F, T, F, F, F, T, T, F, F, T,
        F, T, T, T, F, F, F, F, F, T, T, T, T, F, F, T, F, F, T, F, T, T, T,
        F, F, F, F, T, T, T, T, F, T, F, F, F, F, T, F, F, T, F, F, F, T, F,
        F, T, T, T, T, T, T, F, T, F, F, F, F, T, F, F, F, F,
    },
    {
        F, T, T, T, T, T, T, F, T, F, F, T, F, F, T, T, T, T, T, T, F, T, T,
        T, T, T, T, T, T, T, T, F, T, F, T, T, F, T, F, T, F, F, T, T, T, T,
        T, T, T, T, F, T, T, T, T, F, T, T, T, T, F, T, T, T, T, T, T, T, T,
        F, T, T, T, T, F, F, T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T,
        T, T, T, T, T, T, T, T, T, F, T, T, F, T, T, T, F, T, T, T, T, F, T,
        F, F, T, F, T, F, T, T, T, F, F, T, T, T, F, T, T, F,
    },
    {
        F, F, T, F, F, F, T, F, T, F, T, T, T, F, T, F, T, F, T, T, F, F, F,
        T, F, F, T, F, T, F, T, F, T, T, T, T, T, T, T, T, T, T, T, F, F, F,
        F, T, T, F, F, T, F, F, T, T, T, T, F, T, T, T, F, T, T, T, T, T, F,
        T, T, T, F, T, T, F, F, T, F, T, F, T, F, F, F, F, T, F, T, T, F, T,
        T, T, F, T, T, T, T, F, T, F, T, F, F, T, F, T, T, T, F, T, T, F, T,
        F, F, F, T, T, F, T, F, T, F, F, T, T, F, T, T, F, F,
    },
    {
        F, F, T, T, F, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F,
        F, F, T, F, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        T, F, T, F, F, F, F, T, T, F, F, F, T, F, F, F, T, F, F, F, F, F, F,
        F, F, T, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, T,
        F, F, F, F, F, T, F, F, F, F, F, F, F, T, T, T, F, F, T, F, F, F, T,
        F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, T, F, F,
    },
    {
        F, F, T, T, T, T, T, F, T, F, F, T, T, F, F, F, F, T, F, F, F, T, T,
        F, F, T, F, T, T, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        T, F, T, F, F, F, F, T, T, F, T, F, T, F, F, F, T, T, F, T, T, T, T,
        F, T, T, T, T, F, F, F, F, F, F, F, T, T, F, T, F, F, F, T, T, F, T,
        T, T, F, F, T, T, F, T, F, F, F, F, F, T, T, T, F, F, T, F, T, F, T,
        F, F, F, F, F, F, F, T, F, F, F, T, T, T, F, T, T, F,
    },
    {
        F, T, T, T, F, F, T, T, T, F, T, T, T, T, T, F, F, T, F, F, F, T, T,
        F, F, F, T, T, T, T, T, F, T, F, T, F, T, T, F, F, F, F, F, F, F, F,
        T, F, T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T, F, F, T, T, T,
        T, F, T, F, F, T, T, T, T, F, F, F, T, T, T, T, T, T, F, T, F, T, T,
        F, T, T, F, F, F, T, F, T, T, F, F, F, T, T, T, T, F, T, F, F, T, T,
        F, F, F, F, F, T, F, T, T, F, F, T, T, F, F, T, T, F,
    },
    {
        F, T, T, T, T, T, T, F, T, F, T, T, F, T, T, T, T, F, T, T, F, T, T,
        T, T, T, T, T, T, T, T, T, T, F, F, T, F, T, T, T, T, T, T, T, T, T,
        T, T, T, T, T, T, T, T, F, F, F, T, T, F, T, T, T, T, T, T, T, T, T,
        F, T, T, T, T, F, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, F,
        T, T, T, T, T, T, T, T, T, F, T, T, F, F, T, T, T, T, F, T, T, F, T,
        F, T, T, T, T, F, T, T, T, F, F, T, T, T, T, F, T, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, T, F, F, F,
        T, T, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F, T, F, F, T, F,
        F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F,
        F, F, F, T, F, F, F, F, F, F, T, T, F, F, F, F, F, F, F, F, T, F, F,
        F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, T, T, F, F,
        F, F, T, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F,
    },
    {
        F, F, T, T, T, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F,
        F, F, T, F, T, T, F, T, F, F, F, T, F, F, F, F, T, F, F, F, F, F, T,
        T, T, T, F, F, F, F, T, T, F, T, F, T, F, F, F, T, F, T, F, F, F, F,
        F, T, T, T, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, T, F, T,
        T, F, F, T, F, T, F, F, F, F, F, T, F, T, T, T, F, T, T, F, T, F, T,
        F, F, T, F, F, F, T, T, F, F, F, T, T, T, F, T, T, F,
    },
    {
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F,
        F, F, F, F, F, F, T, T, T, F, F, F, F, F, F, F, F, T, F, F, F, T, F,
        F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, F,
        F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F,
    },
    {
        F, F, F, T, F, T, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F,
        F, F, T, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, T, F, F, F, F, T, F, F, F, F, T, F, F, F, F, T, F, T, F, F, F,
        F, F, F, T, T, F, F, F, F, F, F, F, T, T, F, F, F, F, F, T, T, F, F,
        F, F, F, F, T, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, T,
        F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F,
    },
    {
        F, F, F, F, F, F, F, F, F, F, T, T, F, F, T, F, T, F, F, T, F, F, F,
        F, F, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, T, T, F, F, F,
        F, F, F, F, F, T, F, F, F, F, F, T, F, F, T, T, F, T, F, T, F, F, F,
        F, F, F, F, F, F, F, F, T, F, T, F, T, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, T, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, T, T, F, T, T, F, T, F, F, T, F, F, T, F, F, F, F, F, F, T, T,
        F, F, T, F, T, T, T, T, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F,
        T, F, T, F, F, T, T, T, T, F, F, F, T, T, F, F, T, T, F, F, T, F, T,
        F, F, T, F, T, F, F, T, F, F, F, F, T, T, T, T, F, T, F, T, F, F, T,
        F, T, F, F, T, T, T, F, T, F, F, F, F, T, T, T, F, F, T, F, F, F, T,
        F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, T, F, F,
    },
    {
        F, T, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, T, F, F, F, T, F, T, F,
        T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F,
        T, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, F, T, T, F,
        F, F, F, F, T, F, F, F, T, F, F, T, F, T, F, F, T, F,
    },
    {
        F, T, T, T, T, T, T, F, F, F, F, T, F, F, F, F, T, F, T, T, F, F, T,
        T, T, F, T, F, F, T, F, F, T, T, F, F, T, F, T, F, F, T, F, T, T, F,
        T, F, F, T, F, F, F, F, T, T, T, F, F, F, T, T, T, T, F, F, T, F, T,
        T, T, F, T, F, F, F, F, F, T, T, F, T, F, F, T, F, F, T, F, T, T, T,
        T, T, T, F, T, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, T, T, T,
        F, F, F, F, T, T, F, F, T, F, F, T, F, T, F, T, T, F,
    },
    {
        F, T, T, F, F, T, F, T, F, F, T, F, F, T, T, T, F, F, T, F, F, T, F,
        F, F, T, T, T, F, T, T, F, T, F, T, F, F, F, F, T, T, F, T, T, T, T,
        F, T, T, F, T, T, T, F, T, T, T, T, T, T, F, F, T, F, T, F, F, F, F,
        F, F, T, F, F, F, T, F, F, F, T, T, F, T, T, T, F, F, F, T, F, F, F,
        T, T, T, F, T, T, F, F, T, T, T, F, F, F, F, T, F, F, T, F, F, F, F,
        F, F, T, T, T, T, F, F, F, F, F, F, F, T, F, F, T, F,
    },
    {
        F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F,
        F, F, F, F, T, T, F, F, T, F, F, F, F, F, F, T, F, F, T, T, F, F, F,
        T, F, F, T, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, T,
        F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, F,
        F, F, F, F, F, F, T, F, F, F, T, F, F, F, T, T, F, F, F, F, F, F, F,
        F, F, F, F, F, F, T, F, F, F, F, T, F, F, T, F, T, F,
    },
    {
        F, F, T, F, T, F, F, F, T, F, F, F, F, F, T, F, F, T, F, T, F, T, T,
        F, T, F, T, F, F, T, T, F, T, F, T, F, F, T, F, F, F, F, T, F, T, F,
        T, T, F, T, F, T, T, F, T, F, T, T, F, T, F, F, F, F, T, F, F, F, T,
        F, T, T, F, F, F, F, F, F, F, T, T, F, F, F, T, T, F, T, F, F, T, T,
        T, F, T, F, F, F, T, T, F, F, T, F, F, F, F, T, F, T, F, T, F, F, F,
        F, F, T, F, T, F, T, T, T, F, F, F, F, F, F, F, F, F,
    },
    {
        F, F, F, F, T, F, F, T, F, F, F, F, T, F, F, T, T, T, T, T, F, F, F,
        T, T, F, T, F, F, F, F, T, F, T, T, F, T, F, T, T, T, T, F, T, T, T,
        F, T, F, T, T, F, F, F, F, T, T, F, F, F, F, F, F, F, T, T, F, T, F,
        F, T, F, T, F, F, F, F, F, T, T, T, F, F, F, F, F, F, T, F, T, F, F,
        T, F, T, T, F, F, F, T, F, F, T, T, F, F, F, F, T, T, F, T, T, F, F,
        F, T, T, F, F, T, T, F, F, F, F, T, F, T, T, F, T, F,
    },
    {
        F, F, T, T, F, T, T, F, F, F, F, F, T, F, F, F, T, T, F, T, F, F, F,
        F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F,
        T, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, T, F, T, F,
        F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, T,
        F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T,
        F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F,
    },
    {
        F, F, F, F, F, F, F, T, F, F, T, F, T, T, F, F, F, T, F, T, F, F, F,
        F, T, F, T, F, F, F, F, T, T, T, T, F, T, F, T, F, T, T, T, F, F, F,
        F, F, F, T, T, T, T, F, T, T, T, T, F, T, T, F, F, F, F, F, F, F, F,
        T, F, F, F, F, T, T, F, T, T, F, T, F, F, F, T, T, F, T, F, F, T, F,
        F, F, T, F, F, F, F, F, F, T, T, F, F, F, F, F, T, T, F, T, F, T, F,
        F, T, F, T, F, T, T, F, T, F, F, F, F, F, T, F, F, F,
    },
    {
        F, F, F, F, F, F, F, T, T, F, F, F, F, F, T, T, T, F, F, F, F, F, F,
        F, F, F, F, F, T, T, T, F, T, F, T, T, T, F, F, T, T, F, F, T, F, T,
        F, T, F, F, F, F, F, F, F, F, F, T, T, T, F, F, T, T, F, F, F, F, F,
        T, F, F, F, T, T, T, T, T, F, F, F, F, T, T, F, T, T, F, T, F, F, F,
        T, F, T, T, F, F, F, F, T, F, T, T, F, T, F, T, F, F, T, T, T, F, F,
        F, F, F, F, F, F, F, T, F, F, F, F, T, F, T, T, F, F,
    },
    {
        F, F, T, T, T, F, T, T, T, F, F, F, T, F, F, F, F, T, T, F, F, T, F,
        T, T, T, T, T, T, F, T, T, T, T, T, F, T, F, T, T, T, F, F, F, F, T,
        T, T, T, F, F, F, F, F, T, T, T, F, F, T, F, F, T, F, T, F, T, T, F,
        T, T, T, T, T, T, F, F, F, F, F, F, F, T, F, T, F, F, T, T, T, F, T,
        T, T, T, T, F, T, F, F, F, T, T, T, F, T, F, T, T, T, T, T, T, F, T,
        F, T, T, F, F, T, T, T, F, F, F, T, T, F, T, T, T, F,
    },
    {
        F, T, F, F, F, F, F, F, T, F, T, T, F, T, T, F, F, F, F, F, F, T, T,
        F, F, F, F, T, T, T, F, F, T, F, F, T, F, T, F, F, F, F, T, F, F, F,
        F, F, F, F, F, T, T, T, F, F, F, T, T, T, T, T, F, T, F, F, T, F, T,
        T, F, F, F, F, T, T, T, T, F, F, F, T, F, T, T, T, T, F, T, F, T, F,
        F, T, F, F, T, F, T, F, T, T, F, F, F, F, T, T, F, F, T, F, F, T, F,
        F, F, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, F,
    },
}};

const std::map<Triple, std::size_t> query_to_hole{
    {Triple{1, 1, 1}, 13},  {Triple{1, 1, 2}, 102}, {Triple{1, 1, 3}, 70},
    {Triple{1, 1, 4}, 114}, {Triple{1, 1, 5}, 61},  {Triple{1, 2, 1}, 56},
    {Triple{1, 2, 2}, 121}, {Triple{1, 2, 3}, 75},  {Triple{1, 2, 4}, 14},
    {Triple{1, 2, 5}, 11},  {Triple{1, 3, 1}, 37},  {Triple{1, 3, 2}, 8},
    {Triple{1, 3, 3}, 109}, {Triple{1, 3, 4}, 76},  {Triple{1, 3, 5}, 78},
    {Triple{1, 4, 1}, 34},  {Triple{1, 4, 2}, 117}, {Triple{1, 4, 3}, 41},
    {Triple{1, 4, 4}, 79},  {Triple{1, 4, 5}, 119}, {Triple{1, 5, 1}, 39},
    {Triple{1, 5, 2}, 32},  {Triple{1, 5, 3}, 130}, {Triple{1, 5, 4}, 51},
    {Triple{1, 5, 5}, 42},  {Triple{2, 1, 1}, 55},  {Triple{2, 1, 2}, 85},
    {Triple{2, 1, 3}, 60},  {Triple{2, 1, 4}, 53},  {Triple{2, 1, 5}, 52},
    {Triple{2, 2, 1}, 57},  {Triple{2, 2, 2}, 18},  {Triple{2, 2, 3}, 33},
    {Triple{2, 2, 4}, 91},  {Triple{2, 2, 5}, 124}, {Triple{2, 3, 1}, 35},
    {Triple{2, 3, 2}, 95},  {Triple{2, 3, 3}, 27},  {Triple{2, 3, 4}, 86},
    {Triple{2, 3, 5}, 58},  {Triple{2, 4, 1}, 122}, {Triple{2, 4, 2}, 88},
    {Triple{2, 4, 3}, 103}, {Triple{2, 4, 4}, 50},  {Triple{2, 4, 5}, 43},
    {Triple{2, 5, 1}, 110}, {Triple{2, 5, 2}, 25},  {Triple{2, 5, 3}, 112},
    {Triple{2, 5, 4}, 81},  {Triple{2, 5, 5}, 20},  {Triple{3, 1, 1}, 131},
    {Triple{3, 1, 2}, 111}, {Triple{3, 1, 3}, 67},  {Triple{3, 1, 4}, 77},
    {Triple{3, 1, 5}, 87},  {Triple{3, 2, 1}, 106}, {Triple{3, 2, 2}, 63},
    {Triple{3, 2, 3}, 94},  {Triple{3, 2, 4}, 84},  {Triple{3, 2, 5}, 101},
    {Triple{3, 3, 1}, 127}, {Triple{3, 3, 2}, 132}, {Triple{3, 3, 3}, 68},
    {Triple{3, 3, 4}, 2},   {Triple{3, 3, 5}, 62},  {Triple{3, 4, 1}, 40},
    {Triple{3, 4, 2}, 46},  {Triple{3, 4, 3}, 19},  {Triple{3, 4, 4}, 44},
    {Triple{3, 4, 5}, 36},  {Triple{3, 5, 1}, 96},  {Triple{3, 5, 2}, 104},
    {Triple{3, 5, 3}, 24},  {Triple{3, 5, 4}, 16},  {Triple{3, 5, 5}, 17},
    {Triple{4, 1, 1}, 92},  {Triple{4, 1, 2}, 22},  {Triple{4, 1, 3}, 9},
    {Triple{4, 1, 4}, 23},  {Triple{4, 1, 5}, 38},  {Triple{4, 2, 1}, 72},
    {Triple{4, 2, 2}, 47},  {Triple{4, 2, 3}, 108}, {Triple{4, 2, 4}, 69},
    {Triple{4, 2, 5}, 99},  {Triple{4, 3, 1}, 31},  {Triple{4, 3, 2}, 123},
    {Triple{4, 3, 3}, 3},   {Triple{4, 3, 4}, 30},  {Triple{4, 3, 5}, 15},
    {Triple{4, 4, 1}, 71},  {Triple{4, 4, 2}, 5},   {Triple{4, 4, 3}, 93},
    {Triple{4, 4, 4}, 100}, {Triple{4, 4, 5}, 120}, {Triple{4, 5, 1}, 65},
    {Triple{4, 5, 2}, 118}, {Triple{4, 5, 3}, 48},  {Triple{4, 5, 4}, 45},
    {Triple{4, 5, 5}, 80},  {Triple{5, 1, 1}, 7},   {Triple{5, 1, 2}, 28},
    {Triple{5, 1, 3}, 29},  {Triple{5, 1, 4}, 107}, {Triple{5, 1, 5}, 82},
    {Triple{5, 2, 1}, 49},  {Triple{5, 2, 2}, 4},   {Triple{5, 2, 3}, 89},
    {Triple{5, 2, 4}, 54},  {Triple{5, 2, 5}, 12},  {Triple{5, 3, 1}, 128},
    {Triple{5, 3, 2}, 83},  {Triple{5, 3, 3}, 115}, {Triple{5, 3, 4}, 59},
    {Triple{5, 3, 5}, 64},  {Triple{5, 4, 1}, 98},  {Triple{5, 4, 2}, 26},
    {Triple{5, 4, 3}, 74},  {Triple{5, 4, 4}, 6},   {Triple{5, 4, 5}, 97},
    {Triple{5, 5, 1}, 90},  {Triple{5, 5, 2}, 73},  {Triple{5, 5, 3}, 113},
    {Triple{5, 5, 4}, 129}, {Triple{5, 5, 5}, 66}};

const const std::map<int, std::size_t> card_labels{
    {201, 0},  {798, 0},  {204, 0},  {796, 0},  {206, 1},  {793, 1},  {212, 1},
    {790, 1},  {215, 2},  {786, 2},  {217, 2},  {783, 2},  {220, 3},  {781, 3},
    {223, 3},  {779, 3},  {227, 4},  {776, 4},  {231, 4},  {773, 4},  {233, 5},
    {770, 5},  {237, 5},  {767, 5},  {244, 6},  {765, 6},  {251, 6},  {759, 6},
    {253, 7},  {757, 7},  {256, 7},  {754, 7},  {261, 8},  {750, 8},  {264, 8},
    {747, 8},  {267, 9},  {744, 9},  {270, 9},  {742, 9},  {274, 10}, {740, 10},
    {278, 10}, {738, 10}, {280, 11}, {736, 11}, {282, 11}, {733, 11}, {286, 12},
    {729, 12}, {288, 12}, {725, 12}, {293, 13}, {720, 13}, {296, 13}, {718, 13},
    {302, 14}, {715, 14}, {304, 14}, {710, 14}, {309, 15}, {708, 15}, {312, 15},
    {704, 15}, {315, 16}, {699, 16}, {317, 16}, {696, 16}, {322, 17}, {694, 17},
    {325, 17}, {690, 17}, {329, 18}, {687, 18}, {331, 18}, {684, 18}, {334, 19},
    {680, 19}, {337, 19}, {673, 19}, {339, 20}, {669, 20}, {341, 20}, {667, 20},
    {346, 21}, {664, 21}, {348, 21}, {662, 21}, {350, 22}, {658, 22}, {353, 22},
    {656, 22}, {356, 23}, {653, 23}, {358, 23}, {651, 23}, {360, 24}, {649, 24},
    {365, 24}, {647, 24}, {370, 25}, {645, 25}, {373, 25}, {641, 25}, {376, 26},
    {639, 26}, {378, 26}, {637, 26}, {381, 27}, {635, 27}, {385, 27}, {633, 27},
    {387, 28}, {631, 28}, {390, 28}, {629, 28}, {392, 29}, {627, 29}, {394, 29},
    {621, 29}, {396, 30}, {617, 30}, {401, 30}, {615, 30}, {403, 31}, {613, 31},
    {405, 31}, {610, 31}, {407, 32}, {608, 32}, {410, 32}, {605, 32}, {413, 33},
    {599, 33}, {416, 33}, {597, 33}, {419, 34}, {595, 34}, {423, 34}, {593, 34},
    {429, 35}, {591, 35}, {432, 35}, {589, 35}, {434, 36}, {587, 36}, {437, 36},
    {585, 36}, {440, 37}, {581, 37}, {442, 37}, {579, 37}, {447, 38}, {577, 38},
    {453, 38}, {573, 38}, {455, 39}, {571, 39}, {459, 39}, {567, 39}, {462, 40},
    {564, 40}, {464, 40}, {562, 40}, {470, 41}, {558, 41}, {472, 41}, {553, 41},
    {475, 42}, {550, 42}, {479, 42}, {547, 42}, {481, 43}, {543, 43}, {483, 43},
    {540, 43}, {485, 44}, {536, 44}, {487, 44}, {533, 44}, {491, 45}, {530, 45},
    {495, 45}, {527, 45}, {497, 46}, {523, 46}, {499, 46}, {518, 46}, {503, 47},
    {515, 47}, {505, 47}, {509, 47}, {507, 48}, {506, 48}, {514, 48}, {504, 48},
    {516, 49}, {502, 49}, {520, 49}, {498, 49}, {525, 50}, {496, 50}, {528, 50},
    {492, 50}, {532, 51}, {490, 51}, {534, 51}, {486, 51}, {537, 52}, {484, 52},
    {541, 52}, {482, 52}, {546, 53}, {480, 53}, {549, 53}, {476, 53}, {551, 54},
    {474, 54}, {557, 54}, {471, 54}, {560, 55}, {469, 55}, {563, 55}, {463, 55},
    {566, 56}, {461, 56}, {568, 56}, {458, 56}, {572, 57}, {454, 57}, {576, 57},
    {449, 57}, {578, 58}, {445, 58}, {580, 58}, {441, 58}, {582, 59}, {439, 59},
    {586, 59}, {435, 59}, {588, 60}, {433, 60}, {590, 60}, {430, 60}, {592, 61},
    {424, 61}, {594, 61}, {421, 61}, {596, 62}, {418, 62}, {598, 62}, {414, 62},
    {604, 63}, {412, 63}, {606, 63}, {409, 63}, {609, 64}, {406, 64}, {611, 64},
    {404, 64}, {614, 65}, {402, 65}, {616, 65}, {399, 65}, {618, 66}, {395, 66},
    {625, 66}, {393, 66}, {628, 67}, {391, 67}, {630, 67}, {389, 67}, {632, 68},
    {386, 68}, {634, 68}, {382, 68}, {636, 69}, {379, 69}, {638, 69}, {377, 69},
    {640, 70}, {374, 70}, {643, 70}, {372, 70}, {646, 71}, {369, 71}, {648, 71},
    {362, 71}, {650, 72}, {359, 72}, {652, 72}, {357, 72}, {654, 73}, {355, 73},
    {657, 73}, {352, 73}, {661, 74}, {349, 74}, {663, 74}, {347, 74}, {665, 75},
    {344, 75}, {668, 75}, {340, 75}, {670, 76}, {338, 76}, {677, 76}, {335, 76},
    {681, 77}, {332, 77}, {686, 77}, {330, 77}, {688, 78}, {327, 78}, {691, 78},
    {324, 78}, {695, 79}, {319, 79}, {697, 79}, {316, 79}, {701, 80}, {314, 80},
    {706, 80}, {311, 80}, {709, 81}, {308, 81}, {714, 81}, {303, 81}, {717, 82},
    {299, 82}, {719, 82}, {294, 82}, {723, 83}, {289, 83}, {726, 83}, {287, 83},
    {737, 84}, {279, 84}, {739, 84}, {277, 84}, {741, 85}, {273, 85}, {743, 85},
    {268, 85}, {746, 86}, {266, 86}, {749, 86}, {263, 86}, {751, 87}, {257, 87},
    {755, 87}, {255, 87}, {758, 88}, {252, 88}, {763, 88}, {247, 88}, {766, 89},
    {243, 89}, {769, 89}, {236, 89}, {771, 90}, {232, 90}, {775, 90}, {228, 90},
    {778, 91}, {224, 91}, {780, 91}, {221, 91}, {782, 92}, {219, 92}, {785, 92},
    {216, 92}, {787, 93}, {213, 93}, {792, 93}, {207, 93}, {795, 94}, {205, 94},
    {797, 94}, {202, 94}};
